name: Markdown
description: Add a Markdown content block to your site, or add <code>{{ markdown(content) }}</code> in your templates
namespace: Markdown
model_schema:
  content: text
  filteredContent: text